name: Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
permissions: read-all
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.out -covermode=atomic -short ./...
      - name: Generate Coverage Report
        run: go tool cover -func=coverage.out
      - name: Analyse Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: coverage.out
          local-prefix: github.com/${{ github.repository }}
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0
